### ISSUE TITLE
Question about the ASR and the "--adv 4".

### ISSUE THREAD

**Issue by Sammy42779** [adversarial-for-goodness/Co-Attack#1]
Hi! First of all, thank you for sharing your awesome work.
I have two questions about the calculation of ASR and the meaning of "--adv 4" in the paper.

First, I run this code, and the output is the top-k performance. So, how do you calculate the ASR?
Second, does the "--adv 4" mean your own Co-Attack method instead of attacking modalities independently?

Looking forward to your reply.
Thanks!

**Comment by jiamingzhang94** [comment]
First, run "--adv 0" to get the clean accuracy, then run "--adv 4" to get the adversarial accuracy, and the ASR=clean accuracy-adversarial accuracy.
Second, yes.
