### ISSUE TITLE
The results of attacking Clip model are inconsistent with the paper?

### ISSUE THREAD

**Issue by Eurus-Holmes** [adversarial-for-goodness/Co-Attack#3]
Hi @jiamingzhang94 , thanks for sharing your code. But when I test the results of attacking Clip model on Flickr30k dataset, it seems inconsistent with the paper reported?

Here are my reproduced results and [colab link](https://colab.research.google.com/drive/1ahCro4qpx_ywfkWlCgNT0RCnz54AwZZN?usp=sharing):
```
{'txt_r1': 7.4, 'txt_r5': 17.0, 'txt_r10': 22.7, 'txt_r_mean': 15.699999999999998, 'img_r1': 3.92, 'img_r5': 10.22, 'img_r10': 14.5, 'img_r_mean': 9.546666666666667, 'r_mean': 12.623333333333331}
```

But in the paper:
<img width="822" alt="Screen Shot 2022-10-29 at 23 12 23" src="https://user-images.githubusercontent.com/34226570/198865202-ff693f2c-d862-4b2d-b609-2946283d5c3c.png">

Why is there such a difference?

**Comment by jiamingzhang94** [comment]
Hi @Eurus-Holmes , the reported value is attack success rate while the output of this code is accuracy of adversarial examples. To get ASR, you need to run adv=0 to get the accuracy of original examples, and then ASR=accuracy of original examples - accuracy of adversarial examples.

**Comment by Eurus-Holmes** [comment]
> Hi @Eurus-Holmes , the reported value is attack success rate while the output of this code is accuracy of adversarial examples. To get ASR, you need to run adv=0 to get the accuracy of original examples, and then ASR=accuracy of original examples - accuracy of adversarial examples.

Oh I see, thanks!
