### ISSUE TITLE
Where did you get the refcoco+_train.json, refcoco+_val.json, refcoco+_test.json, dets.json, and cocos.json files in configs/Grounding.yaml?

### ISSUE THREAD

**Issue by HeBangYan** [adversarial-for-goodness/Co-Attack#7]
Hi, thanks for the excellent work. :)

I want to know how to get these json files: refcoco+_train.json, refcoco+_val.json, refcoco+_test.json, dets.json, and cocos.json.

**Comment by jiamingzhang94** [comment]
Hi,

Dataset json files for downstream tasks [[ALBEF github]](https://github.com/salesforce/ALBEF)

**Comment by HeBangYan** [comment]
Many thanks. 👍🏻
